### ISSUE TITLE
Revit 2025 Compatibility

### ISSUE THREAD

**Issue by iHoody** [ricaun-io/ricaun.Revit.CefSharp#6]
Now that Revit 2025 had been released, it would be great if we can get this added so that the correct versions of cefsharp/dependencies are used.

**Comment by ricaun** [comment]
Hello @iHoody 

I add a prerelease version for testing for Revit 2025.

If you add this code should use the prerelease version or `2025.0.0-alpha`.

```xml
<PackageReference Include="ricaun.Revit.CefSharp" Version="$(RevitVersion).*-*" IncludeAssets="build; compile" PrivateAssets="All" />
```

* https://www.nuget.org/packages/ricaun.Revit.CefSharp/2025.0.0-alpha

I need to validate in a separated project, but looks like is working fine.

**Comment by iHoody** [comment]
Looks like it is working fine for me too.

**Comment by ricaun** [comment]
Great, I tested as well and works fine!
